version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}

  migrate:
    container_name: migrate-tool
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://${PG_USER}:${PG_PASSWORD}@database:5432/${PG_DB}?sslmode=disable", "up"]
    depends_on:
      - database

  httpserver:
    container_name: httpserver
    build:
      context: ./
      dockerfile: ./docker/http/Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8080:8080

  telegrambot:
    container_name: telegrambot
    build:
      context: ./
      dockerfile: ./docker/bot/Dockerfile
    env_file:
      - .env
    depends_on:
      - database
