version: '3.9'

services:
  db:
    container_name: postgres-db
    image: postgres:15.1-alpine
    restart: always
    networks:
      new:
        aliases:
          - database
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
    
  migrate:
    container_name: migrate-tool
    image: migrate/migrate
    networks:
      new:
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://${PG_USER}:${PG_PASSWORD}@database:5432/${PG_DB}?sslmode=disable", "up"]
    depends_on:
      - db
  
  httpserver:
    container_name: metricserver
    build:
      context: ./
      dockerfile: ./docker/http/Dockerfile
    environment:
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - db

  telegrambot:
    container_name: telegrambot
    build:
      context: ./
      dockerfile: ./docker/bot/Dockerfile
    environment:
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - TG_TOKEN=${TG_TOKEN}
    ports:
      - 8080:8090
    depends_on:
      - db

networks:
  new: