app:
  name: "ddos-guard-test"
  version: "1.0.0"

http:
  port: "8080"

logger:
  log_level: "debug"

postgres:
  host: "localhost"
  port: "5432"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"
